// Code generated by protoc-gen-orm-go. DO NOT EDIT.
// source: apptest/tenant.proto.proto

package apptest

func TenantById(v []byte) *TenantRef {
	x := &TenantRef{}
	x.SetId(v)
	return x
}
func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}
