// Code generated by protoc-gen-orm-go. DO NOT EDIT.
// source: apptest/tenant.proto.proto

package apptest

import (
	bytes "bytes"
)

func (x *Tenant) Pick() *TenantRef {
	return TenantById(x.GetId())
}

func (x *TenantRef) Picks(v *Tenant) bool {
	switch x.WhichKey() {
	case TenantRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func TenantById(v []byte) *TenantRef {
	x := &TenantRef{}
	x.SetId(v)
	return x
}

func (x *User) Pick() *UserRef {
	return UserById(x.GetId())
}

func (x *UserRef) Picks(v *User) bool {
	switch x.WhichKey() {
	case UserRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case UserRef_Alias_case:
		x := x.GetAlias()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func UserByAlias(alias string, tenant *TenantRef) *UserRefByAlias {
	x := &UserRefByAlias{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return x
}

func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}
