// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *TenantRef) Pick() *TenantGetRequest {
	return TenantGetRequest_builder{Ref: x}.Build()
}

func (x *Tenant) Ref() *TenantRef {
	if v := x.GetId(); len(v) > 0 {
		return TenantById(v)
	}

	return nil
}

func (x *Tenant) Pick() *TenantGetRequest {
	return x.Ref().Pick()
}

func (x *TenantRef) Picks(v *Tenant) bool {
	switch x.WhichKey() {
	case TenantRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	default:
		return false
	}
}

func (x *TenantGetRequest) WithSelect(f func(s *TenantSelect)) *TenantGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&TenantSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Tenant) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Tenant) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func TenantById(v []byte) *TenantRef {
	x := &TenantRef{}
	x.SetId(v)
	return x
}

func TenantGetById(v []byte) *TenantGetRequest {
	return TenantGetRequest_builder{Ref: TenantById(v)}.Build()
}

func (x *UserRef) Pick() *UserGetRequest {
	return UserGetRequest_builder{Ref: x}.Build()
}

func (x *User) Ref() *UserRef {
	if v := x.GetId(); len(v) > 0 {
		return UserById(v)
	}
	{
		v1 := x.GetAlias()
		v2 := x.GetTenant()
		if len(v1) > 0 && v2 != nil {
			return UserByAlias(v1, v2.Ref())
		}
	}

	return nil
}

func (x *User) Pick() *UserGetRequest {
	return x.Ref().Pick()
}

func (x *UserRef) Picks(v *User) bool {
	switch x.WhichKey() {
	case UserRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case UserRef_Alias_case:
		x := x.GetAlias()
		return (x.GetAlias() == v.GetAlias()) &&
			(x.GetTenant().Picks(v.GetTenant()))
	default:
		return false
	}
}

func (x *UserGetRequest) WithSelect(f func(s *UserSelect)) *UserGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&UserSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *User) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *User) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func UserById(v []byte) *UserRef {
	x := &UserRef{}
	x.SetId(v)
	return x
}

func UserGetById(v []byte) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserById(v)}.Build()
}

func UserByAlias(alias string, tenant *TenantRef) *UserRef {
	x := &UserRefByAlias{}
	x.SetAlias(alias)
	x.SetTenant(tenant)
	return UserRef_builder{Alias: x}.Build()
}

func UserGetByAlias(alias string, tenant *TenantRef) *UserGetRequest {
	return UserGetRequest_builder{Ref: UserByAlias(alias, tenant)}.Build()
}
