// Code generated by protoc-gen-orm-go. DO NOT EDIT.

// Package apptest holds the messages of the schema, the service servers
// generated from them, and the pieces every implementation of those servers
// shares.
//
// A server is a [Server], which is nothing but a set of those service
// servers. Implementations are stacked on top of each other: one of them
// runs the queries against the database and every other one wraps it to add
// a behaviour of its own, so a request walks the stack from the outermost
// server down to the one that answers it. [Build] does the stacking,
// [Overlay] is what a layer embeds to implement only the services it cares
// about, and [Iter], [Find] and [SinkOf] look into a stack that was built.
//
// Whatever a layer can do besides answering a service is found with [Find]
// rather than added to [Server]. That is what keeps [Server] the generated
// set it is: a layer that holds a database, or a connection, or anything
// else the others need, is asked for by what it can do, and every other
// layer stays as narrow as it was written.
package apptest

import (
	fmt "fmt"
	grpc "google.golang.org/grpc"
	iter "iter"
)

type Server interface {
	Tenant() TenantServiceServer
	User() UserServiceServer
}

func RegisterServer(g *grpc.Server, s Server) {
	RegisterTenantServiceServer(g, s.Tenant())
	RegisterUserServiceServer(g, s.User())
}

type UnimplementedServer struct {
	TenantServer TenantServiceServer
	UserServer   UserServiceServer
}

func (UnimplementedServer) Tenant() TenantServiceServer { return UnimplementedTenantServiceServer{} }
func (UnimplementedServer) User() UserServiceServer     { return UnimplementedUserServiceServer{} }

type StaticServer struct {
	TenantServer TenantServiceServer
	UserServer   UserServiceServer
}

func (s StaticServer) Tenant() TenantServiceServer { return s.TenantServer }
func (s StaticServer) User() UserServiceServer     { return s.UserServer }

type Client interface {
	Tenant() TenantServiceClient
	User() UserServiceClient
}

func NewClient(c *grpc.ClientConn) Client {
	return &client{
		_Tenant: NewTenantServiceClient(c),
		_User:   NewUserServiceClient(c),
	}
}

type client struct {
	_Tenant TenantServiceClient
	_User   UserServiceClient
}

func (c *client) Tenant() TenantServiceClient { return c._Tenant }
func (c *client) User() UserServiceClient     { return c._User }

// Middleware is a server that delegates to another server.
type Middleware interface {
	Next() Server
}

// Iter yields `s` and, as long as they are middlewares, the servers behind
// it, from the outermost one to the one that handles the request.
func Iter(s Server) iter.Seq[Server] {
	return func(yield func(Server) bool) {
		for s != nil {
			if !yield(s) {
				return
			}

			mw, ok := s.(Middleware)
			if !ok {
				return
			}

			s = mw.Next()
		}
	}
}

// Find returns the outermost server in the stack that is a `T`.
//
// It is how a stack answers for something that is not a service. A layer
// that owns a database, or a connection, or anything else the others need
// is reached by asking the stack for what can do it, rather than by every
// layer carrying it or by [Server] growing a method for it.
//
// `T` is unconstrained on purpose. The question is asked two ways -- by the
// concrete type of a layer, and by an interface naming the one thing the
// caller needs -- and a constraint of Server would admit only the first,
// since an interface with one method on it does not implement Server. The
// cost is that a `T` no server could ever be is a legal question with a
// false answer.
func Find[T any](s Server) (T, bool) {
	for s := range Iter(s) {
		if v, ok := s.(T); ok {
			return v, true
		}
	}

	var zero T
	return zero, false
}

// SinkOf returns the server the stack ends at, which is the one the others
// were built in front of and the only one that answers out of a database
// rather than by asking somebody else.
//
// It is the same server [Build] was given, and it is named the same way.
// What is at the end is not always what a caller means, though: reach for
// [Find] when there is a particular server in mind, and keep this for when
// the stack itself is the subject.
func SinkOf(s Server) Server {
	for v := range Iter(s) {
		s = v
	}
	return s
}

// Overlay is a middleware that forwards every service it does not override
// to the next server. Embed it to implement only the services of interest:
//
//	type Server struct {
//		Overlay
//	}
//
//	func (s Server) Tenant() TenantServiceServer { ... }
type Overlay struct {
	Server
}

func NewOverlay(next Server) Overlay {
	return Overlay{next}
}

func (s Overlay) Next() Server {
	return s.Server
}

// Builder makes a server that sits in front of `next`. Building may fail
// since a server is free to open the resources it needs, or to reject the
// settings it was given, while it is made.
type Builder interface {
	Build(next Server) (Server, error)
}

type BuilderFunc func(next Server) (Server, error)

func (f BuilderFunc) Build(next Server) (Server, error) {
	return f(next)
}

// Build stacks the given middlewares on top of `sink`. Each builder wraps
// the result of the previous one, so the last builder given handles the
// request first:
//
//	Build(sink, core.Build(), log.Build())
//	// log -> core -> sink
//
// It stops at the first builder that fails, reporting it by its type.
func Build(sink Server, mws ...Builder) (Server, error) {
	s := sink
	for _, mw := range mws {
		v, err := mw.Build(s)
		if err != nil {
			return nil, fmt.Errorf("%T: %w", mw, err)
		}

		s = v
	}

	return s, nil
}
