// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package apptest

import (
	grpc "google.golang.org/grpc"
)

type Server interface {
	Tenant() TenantServiceServer
	User() UserServiceServer
}

func RegisterServer(g *grpc.Server, s Server) {
	RegisterTenantServiceServer(g, s.Tenant())
	RegisterUserServiceServer(g, s.User())
}

type UnimplementedServer struct {
	TenantServer TenantServiceServer
	UserServer   UserServiceServer
}

func (UnimplementedServer) Tenant() TenantServiceServer { return UnimplementedTenantServiceServer{} }
func (UnimplementedServer) User() UserServiceServer     { return UnimplementedUserServiceServer{} }

type StaticServer struct {
	TenantServer TenantServiceServer
	UserServer   UserServiceServer
}

func (s *StaticServer) Tenant() TenantServiceServer { return s.TenantServer }
func (s *StaticServer) User() UserServiceServer     { return s.UserServer }

type Client interface {
	Tenant() TenantServiceClient
	User() UserServiceClient
}

func NewClient(c *grpc.ClientConn) Client {
	return &client{
		_Tenant: NewTenantServiceClient(c),
		_User:   NewUserServiceClient(c),
	}
}

type client struct {
	_Tenant TenantServiceClient
	_User   UserServiceClient
}

func (c *client) Tenant() TenantServiceClient { return c._Tenant }
func (c *client) User() UserServiceClient     { return c._User }
