// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: apptest/user.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: apptest/user_svc.g.proto

package apptest

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Realm       []byte                 `protobuf:"bytes,8,opt,name=realm"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *UserAddRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserAddRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserAddRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UserAddRequest) GetRealm() []byte {
	if x != nil {
		return x.xxx_hidden_Realm
	}
	return nil
}

func (x *UserAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *UserAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *UserAddRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *UserAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *UserAddRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *UserAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *UserAddRequest) SetRealm(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Realm = v
}

func (x *UserAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *UserAddRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserAddRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserAddRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *UserAddRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *UserAddRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = nil
}

func (x *UserAddRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = nil
}

func (x *UserAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type UserAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Tenant      *TenantRef
	Alias       *string
	Name        *string
	Labels      map[string]string
	Realm       []byte
	DateCreated *timestamppb.Timestamp
}

func (b0 UserAddRequest_builder) Build() *UserAddRequest {
	m0 := &UserAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Realm = b.Realm
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type UserRefByAlias struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,2,opt,name=tenant"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRefByAlias) Reset() {
	*x = UserRefByAlias{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefByAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefByAlias) ProtoMessage() {}

func (x *UserRefByAlias) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRefByAlias) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserRefByAlias) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserRefByAlias) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserRefByAlias) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *UserRefByAlias) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserRefByAlias) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserRefByAlias) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Alias = nil
}

func (x *UserRefByAlias) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

type UserRefByAlias_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Alias  *string
	Tenant *TenantRef
}

func (b0 UserRefByAlias_builder) Build() *UserRefByAlias {
	m0 := &UserRefByAlias{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_Tenant = b.Tenant
	return m0
}

type UserRefByRealm struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Realm       []byte                 `protobuf:"bytes,8,opt,name=realm"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,4,opt,name=alias"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserRefByRealm) Reset() {
	*x = UserRefByRealm{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRefByRealm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRefByRealm) ProtoMessage() {}

func (x *UserRefByRealm) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRefByRealm) GetRealm() []byte {
	if x != nil {
		return x.xxx_hidden_Realm
	}
	return nil
}

func (x *UserRefByRealm) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserRefByRealm) SetRealm(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Realm = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UserRefByRealm) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UserRefByRealm) HasRealm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserRefByRealm) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserRefByRealm) ClearRealm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Realm = nil
}

func (x *UserRefByRealm) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

type UserRefByRealm_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Realm []byte
	Alias *string
}

func (b0 UserRefByRealm_builder) Build() *UserRefByRealm {
	m0 := &UserRefByRealm{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Realm != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Realm = b.Realm
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Alias = b.Alias
	}
	return m0
}

type UserRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isUserRef_Key          `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserRef) Reset() {
	*x = UserRef{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRef) ProtoMessage() {}

func (x *UserRef) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*userRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *UserRef) GetAlias() *UserRefByAlias {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*userRef_Alias); ok {
			return x.Alias
		}
	}
	return nil
}

func (x *UserRef) GetRealm() *UserRefByRealm {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*userRef_Realm); ok {
			return x.Realm
		}
	}
	return nil
}

func (x *UserRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &userRef_Id{v}
}

func (x *UserRef) SetAlias(v *UserRefByAlias) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &userRef_Alias{v}
}

func (x *UserRef) SetRealm(v *UserRefByRealm) {
	if v == nil {
		x.xxx_hidden_Key = nil
		return
	}
	x.xxx_hidden_Key = &userRef_Realm{v}
}

func (x *UserRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *UserRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*userRef_Id)
	return ok
}

func (x *UserRef) HasAlias() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*userRef_Alias)
	return ok
}

func (x *UserRef) HasRealm() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*userRef_Realm)
	return ok
}

func (x *UserRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *UserRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*userRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *UserRef) ClearAlias() {
	if _, ok := x.xxx_hidden_Key.(*userRef_Alias); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *UserRef) ClearRealm() {
	if _, ok := x.xxx_hidden_Key.(*userRef_Realm); ok {
		x.xxx_hidden_Key = nil
	}
}

const UserRef_Key_not_set_case case_UserRef_Key = 0
const UserRef_Id_case case_UserRef_Key = 1
const UserRef_Alias_case case_UserRef_Key = 4
const UserRef_Realm_case case_UserRef_Key = 8

func (x *UserRef) WhichKey() case_UserRef_Key {
	if x == nil {
		return UserRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *userRef_Id:
		return UserRef_Id_case
	case *userRef_Alias:
		return UserRef_Alias_case
	case *userRef_Realm:
		return UserRef_Realm_case
	default:
		return UserRef_Key_not_set_case
	}
}

type UserRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id    []byte
	Alias *UserRefByAlias
	Realm *UserRefByRealm
	// -- end of xxx_hidden_Key
}

func (b0 UserRef_builder) Build() *UserRef {
	m0 := &UserRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &userRef_Id{b.Id}
	}
	if b.Alias != nil {
		x.xxx_hidden_Key = &userRef_Alias{b.Alias}
	}
	if b.Realm != nil {
		x.xxx_hidden_Key = &userRef_Realm{b.Realm}
	}
	return m0
}

type case_UserRef_Key protoreflect.FieldNumber

func (x case_UserRef_Key) String() string {
	md := file_apptest_user_svc_g_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isUserRef_Key interface {
	isUserRef_Key()
}

type userRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type userRef_Alias struct {
	Alias *UserRefByAlias `protobuf:"bytes,4,opt,name=alias,oneof"`
}

type userRef_Realm struct {
	Realm *UserRefByRealm `protobuf:"bytes,8,opt,name=realm,oneof"`
}

func (*userRef_Id) isUserRef_Key() {}

func (*userRef_Alias) isUserRef_Key() {}

func (*userRef_Realm) isUserRef_Key() {}

type UserSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Tenant      *TenantSelect          `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_Realm       bool                   `protobuf:"varint,8,opt,name=realm"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserSelect) Reset() {
	*x = UserSelect{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSelect) ProtoMessage() {}

func (x *UserSelect) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *UserSelect) GetTenant() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *UserSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *UserSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *UserSelect) GetRealm() bool {
	if x != nil {
		return x.xxx_hidden_Realm
	}
	return false
}

func (x *UserSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *UserSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *UserSelect) SetTenant(v *TenantSelect) {
	x.xxx_hidden_Tenant = v
}

func (x *UserSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *UserSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *UserSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *UserSelect) SetRealm(v bool) {
	x.xxx_hidden_Realm = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *UserSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *UserSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserSelect) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UserSelect) HasRealm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UserSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *UserSelect) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *UserSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = false
}

func (x *UserSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = false
}

func (x *UserSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Labels = false
}

func (x *UserSelect) ClearRealm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Realm = false
}

func (x *UserSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateCreated = false
}

type UserSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Tenant      *TenantSelect
	Alias       *bool
	Name        *bool
	Labels      *bool
	Realm       *bool
	DateCreated *bool
}

func (b0 UserSelect_builder) Build() *UserSelect {
	m0 := &UserSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_All = *b.All
	}
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.Realm != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Realm = *b.Realm
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type UserGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *UserSelect            `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserGetRequest) Reset() {
	*x = UserGetRequest{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetRequest) ProtoMessage() {}

func (x *UserGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserGetRequest) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserGetRequest) GetSelect() *UserSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *UserGetRequest) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserGetRequest) SetSelect(v *UserSelect) {
	x.xxx_hidden_Select = v
}

func (x *UserGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *UserGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *UserGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type UserGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *UserRef
	Select *UserSelect
}

func (b0 UserGetRequest_builder) Build() *UserGetRequest {
	m0 := &UserGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type UserPatchRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref         *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Tenant      *TenantRef             `protobuf:"bytes,4,opt,name=tenant"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name        *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Realm       []byte                 `protobuf:"bytes,16,opt,name=realm"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserPatchRequest) Reset() {
	*x = UserPatchRequest{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPatchRequest) ProtoMessage() {}

func (x *UserPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserPatchRequest) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserPatchRequest) GetTenant() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *UserPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *UserPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *UserPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *UserPatchRequest) GetRealm() []byte {
	if x != nil {
		return x.xxx_hidden_Realm
	}
	return nil
}

func (x *UserPatchRequest) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserPatchRequest) SetTenant(v *TenantRef) {
	x.xxx_hidden_Tenant = v
}

func (x *UserPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *UserPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *UserPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *UserPatchRequest) SetRealm(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Realm = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *UserPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserPatchRequest) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *UserPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserPatchRequest) HasRealm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *UserPatchRequest) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *UserPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Alias = nil
}

func (x *UserPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Name = nil
}

func (x *UserPatchRequest) ClearRealm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Realm = nil
}

type UserPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *UserRef
	Tenant *TenantRef
	Alias  *string
	Name   *string
	Labels map[string]string
	Realm  []byte
}

func (b0 UserPatchRequest_builder) Build() *UserPatchRequest {
	m0 := &UserPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Tenant = b.Tenant
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Labels = b.Labels
	if b.Realm != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Realm = b.Realm
	}
	return m0
}

type UserApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *UserRef               `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserApplyRequest) Reset() {
	*x = UserApplyRequest{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserApplyRequest) ProtoMessage() {}

func (x *UserApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserApplyRequest) GetRef() *UserRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *UserApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *UserApplyRequest) SetRef(v *UserRef) {
	x.xxx_hidden_Ref = v
}

func (x *UserApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *UserApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *UserApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *UserApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *UserApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type UserApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *UserRef
	Patch *patchpb.Patch
}

func (b0 UserApplyRequest_builder) Build() *UserApplyRequest {
	m0 := &UserApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

type UserEraseResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Erased      bool                   `protobuf:"varint,1,opt,name=erased"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserEraseResponse) Reset() {
	*x = UserEraseResponse{}
	mi := &file_apptest_user_svc_g_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEraseResponse) ProtoMessage() {}

func (x *UserEraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apptest_user_svc_g_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserEraseResponse) GetErased() bool {
	if x != nil {
		return x.xxx_hidden_Erased
	}
	return false
}

func (x *UserEraseResponse) SetErased(v bool) {
	x.xxx_hidden_Erased = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *UserEraseResponse) HasErased() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserEraseResponse) ClearErased() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Erased = false
}

type UserEraseResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Erased is whether this call is the one that erased the row.
	//
	// False for a row that was already gone, was never there, or is out
	// of this caller's reach -- which are one answer on purpose, and the
	// reason the RPC does not fail instead.
	Erased *bool
}

func (b0 UserEraseResponse_builder) Build() *UserEraseResponse {
	m0 := &UserEraseResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Erased != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Erased = *b.Erased
	}
	return m0
}

var File_apptest_user_svc_g_proto protoreflect.FileDescriptor

const file_apptest_user_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x18apptest/user_svc.g.proto\x12\aapptest\x1a\x1aapptest/tenant_svc.g.proto\x1a\x12apptest/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\"\xd1\x02\n" +
	"\x0eUserAddRequest\x12\x15\n" +
	"\x02id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x02id\x12*\n" +
	"\x06tenant\x18\x02 \x01(\v2\x12.apptest.TenantRefR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12;\n" +
	"\x06labels\x18\a \x03(\v2#.apptest.UserAddRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\x05realm\x18\b \x01(\fB\x05\xaa\x01\x02\b\x02R\x05realm\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x0eUserRefByAlias\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12*\n" +
	"\x06tenant\x18\x02 \x01(\v2\x12.apptest.TenantRefR\x06tenant\"<\n" +
	"\x0eUserRefByRealm\x12\x14\n" +
	"\x05realm\x18\b \x01(\fR\x05realm\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\"\x84\x01\n" +
	"\aUserRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12/\n" +
	"\x05alias\x18\x04 \x01(\v2\x17.apptest.UserRefByAliasH\x00R\x05alias\x12/\n" +
	"\x05realm\x18\b \x01(\v2\x17.apptest.UserRefByRealmH\x00R\x05realmB\x05\n" +
	"\x03key\"\xc8\x01\n" +
	"\n" +
	"UserSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12-\n" +
	"\x06tenant\x18\x02 \x01(\v2\x15.apptest.TenantSelectR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12\x14\n" +
	"\x05realm\x18\b \x01(\bR\x05realm\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"a\n" +
	"\x0eUserGetRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.apptest.UserRefR\x03ref\x12+\n" +
	"\x06select\x18\x02 \x01(\v2\x13.apptest.UserSelectR\x06select\"\x9c\x02\n" +
	"\x10UserPatchRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.apptest.UserRefR\x03ref\x12*\n" +
	"\x06tenant\x18\x04 \x01(\v2\x12.apptest.TenantRefR\x06tenant\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12=\n" +
	"\x06labels\x18\x0e \x03(\v2%.apptest.UserPatchRequest.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05realm\x18\x10 \x01(\fR\x05realm\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x10UserApplyRequest\x12\"\n" +
	"\x03ref\x18\x01 \x01(\v2\x10.apptest.UserRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch\"+\n" +
	"\x11UserEraseResponse\x12\x16\n" +
	"\x06erased\x18\x01 \x01(\bR\x06erased2\x88\x02\n" +
	"\vUserService\x12-\n" +
	"\x03Add\x12\x17.apptest.UserAddRequest\x1a\r.apptest.User\x12-\n" +
	"\x03Get\x12\x17.apptest.UserGetRequest\x1a\r.apptest.User\x121\n" +
	"\x05Patch\x12\x19.apptest.UserPatchRequest\x1a\r.apptest.User\x121\n" +
	"\x05Apply\x12\x19.apptest.UserApplyRequest\x1a\r.apptest.User\x125\n" +
	"\x05Erase\x12\x10.apptest.UserRef\x1a\x1a.apptest.UserEraseResponseB<Z:github.com/protobuf-orm/protoc-gen-orm-go/internal/apptestb\beditionsp\xe8\a"

var file_apptest_user_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apptest_user_svc_g_proto_goTypes = []any{
	(*UserAddRequest)(nil),        // 0: apptest.UserAddRequest
	(*UserRefByAlias)(nil),        // 1: apptest.UserRefByAlias
	(*UserRefByRealm)(nil),        // 2: apptest.UserRefByRealm
	(*UserRef)(nil),               // 3: apptest.UserRef
	(*UserSelect)(nil),            // 4: apptest.UserSelect
	(*UserGetRequest)(nil),        // 5: apptest.UserGetRequest
	(*UserPatchRequest)(nil),      // 6: apptest.UserPatchRequest
	(*UserApplyRequest)(nil),      // 7: apptest.UserApplyRequest
	(*UserEraseResponse)(nil),     // 8: apptest.UserEraseResponse
	nil,                           // 9: apptest.UserAddRequest.LabelsEntry
	nil,                           // 10: apptest.UserPatchRequest.LabelsEntry
	(*TenantRef)(nil),             // 11: apptest.TenantRef
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*TenantSelect)(nil),          // 13: apptest.TenantSelect
	(*patchpb.Patch)(nil),         // 14: patch.Patch
	(*User)(nil),                  // 15: apptest.User
}
var file_apptest_user_svc_g_proto_depIdxs = []int32{
	11, // 0: apptest.UserAddRequest.tenant:type_name -> apptest.TenantRef
	9,  // 1: apptest.UserAddRequest.labels:type_name -> apptest.UserAddRequest.LabelsEntry
	12, // 2: apptest.UserAddRequest.date_created:type_name -> google.protobuf.Timestamp
	11, // 3: apptest.UserRefByAlias.tenant:type_name -> apptest.TenantRef
	1,  // 4: apptest.UserRef.alias:type_name -> apptest.UserRefByAlias
	2,  // 5: apptest.UserRef.realm:type_name -> apptest.UserRefByRealm
	13, // 6: apptest.UserSelect.tenant:type_name -> apptest.TenantSelect
	3,  // 7: apptest.UserGetRequest.ref:type_name -> apptest.UserRef
	4,  // 8: apptest.UserGetRequest.select:type_name -> apptest.UserSelect
	3,  // 9: apptest.UserPatchRequest.ref:type_name -> apptest.UserRef
	11, // 10: apptest.UserPatchRequest.tenant:type_name -> apptest.TenantRef
	10, // 11: apptest.UserPatchRequest.labels:type_name -> apptest.UserPatchRequest.LabelsEntry
	3,  // 12: apptest.UserApplyRequest.ref:type_name -> apptest.UserRef
	14, // 13: apptest.UserApplyRequest.patch:type_name -> patch.Patch
	0,  // 14: apptest.UserService.Add:input_type -> apptest.UserAddRequest
	5,  // 15: apptest.UserService.Get:input_type -> apptest.UserGetRequest
	6,  // 16: apptest.UserService.Patch:input_type -> apptest.UserPatchRequest
	7,  // 17: apptest.UserService.Apply:input_type -> apptest.UserApplyRequest
	3,  // 18: apptest.UserService.Erase:input_type -> apptest.UserRef
	15, // 19: apptest.UserService.Add:output_type -> apptest.User
	15, // 20: apptest.UserService.Get:output_type -> apptest.User
	15, // 21: apptest.UserService.Patch:output_type -> apptest.User
	15, // 22: apptest.UserService.Apply:output_type -> apptest.User
	8,  // 23: apptest.UserService.Erase:output_type -> apptest.UserEraseResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_apptest_user_svc_g_proto_init() }
func file_apptest_user_svc_g_proto_init() {
	if File_apptest_user_svc_g_proto != nil {
		return
	}
	file_apptest_tenant_svc_g_proto_init()
	file_apptest_user_proto_init()
	file_apptest_user_svc_g_proto_msgTypes[3].OneofWrappers = []any{
		(*userRef_Id)(nil),
		(*userRef_Alias)(nil),
		(*userRef_Realm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apptest_user_svc_g_proto_rawDesc), len(file_apptest_user_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apptest_user_svc_g_proto_goTypes,
		DependencyIndexes: file_apptest_user_svc_g_proto_depIdxs,
		MessageInfos:      file_apptest_user_svc_g_proto_msgTypes,
	}.Build()
	File_apptest_user_svc_g_proto = out.File
	file_apptest_user_svc_g_proto_goTypes = nil
	file_apptest_user_svc_g_proto_depIdxs = nil
}
